import { useEffect, useState } from 'react';
import { useFlow } from '../../context/FlowContext';

export default function AdminPanel() {
  const { adminUsers, loadAdminUsers, updateAdminUser, createAdminUser, authUser, authError, setAuthError } = useFlow();
  const [editingId, setEditingId] = useState(null); const [draftName, setDraftName] = useState(''); const [isLoading, setIsLoading] = useState(true); const [savingId, setSavingId] = useState(null); const [isCreating, setIsCreating] = useState(false);
  const [newAccount, setNewAccount] = useState({ name: '', email: '', password: '', role: 'user' });
  useEffect(() => { loadAdminUsers().finally(() => setIsLoading(false)); }, []);
  const beginEdit = (user) => { setEditingId(user.id); setDraftName(user.name); setAuthError(''); };
  const saveName = async (user) => { setSavingId(user.id); try { await updateAdminUser(user.id, { name: draftName }); setEditingId(null); } finally { setSavingId(null); } };
  const updateRole = async (user, role) => { setSavingId(user.id); try { await updateAdminUser(user.id, { role }); } finally { setSavingId(null); } };
  const toggleBan = async (user) => { setSavingId(user.id); try { await updateAdminUser(user.id, { isBanned: !user.isBanned }); } finally { setSavingId(null); } };
  const createAccount = async (event) => { event.preventDefault(); setIsCreating(true); setAuthError(''); try { await createAdminUser(newAccount); setNewAccount({ name: '', email: '', password: '', role: 'user' }); } finally { setIsCreating(false); } };
  return <section className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-12"><div className="rounded-[2rem] border border-surface-container bg-surface-container-lowest p-6 shadow-[0_5px_0_#121214] sm:p-8"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><span className="text-xs font-bold uppercase tracking-widest text-primary">Admin workspace</span><h1 className="mt-1 text-3xl font-bold tracking-tight text-on-surface">User Management</h1><p className="mt-1 text-sm font-medium text-on-surface-variant">Create new accounts, edit roles, or block accounts. Access is restricted on the server.</p></div><span className="rounded-full bg-primary-container px-3 py-1.5 text-xs font-bold text-on-primary-container">{adminUsers.length} accounts</span></div>
    {authError && <p role="alert" className="mt-5 rounded-xl bg-error-container px-4 py-3 text-xs font-semibold text-on-error-container">{authError}</p>}
    <form onSubmit={createAccount} className="mt-6 grid gap-3 rounded-2xl bg-surface-container-low p-4 md:grid-cols-[1.1fr_1.2fr_1fr_140px_auto]"><label className="text-xs font-bold text-on-surface">Name<input required minLength="2" maxLength="80" value={newAccount.name} onChange={(event) => setNewAccount({ ...newAccount, name: event.target.value })} className="mt-1.5 w-full rounded-xl bg-surface-container-lowest px-3 py-2.5 text-sm font-normal outline-none focus:ring-2 focus:ring-primary/30" placeholder="Full name" /></label><label className="text-xs font-bold text-on-surface">Email<input required type="email" value={newAccount.email} onChange={(event) => setNewAccount({ ...newAccount, email: event.target.value })} className="mt-1.5 w-full rounded-xl bg-surface-container-lowest px-3 py-2.5 text-sm font-normal outline-none focus:ring-2 focus:ring-primary/30" placeholder="name@email.com" /></label><label className="text-xs font-bold text-on-surface">Password<input required type="password" minLength="8" maxLength="128" value={newAccount.password} onChange={(event) => setNewAccount({ ...newAccount, password: event.target.value })} className="mt-1.5 w-full rounded-xl bg-surface-container-lowest px-3 py-2.5 text-sm font-normal outline-none focus:ring-2 focus:ring-primary/30" placeholder="At least 8 characters" /></label><label className="text-xs font-bold text-on-surface">Role<select value={newAccount.role} onChange={(event) => setNewAccount({ ...newAccount, role: event.target.value })} className="mt-1.5 w-full rounded-xl bg-surface-container-lowest px-3 py-2.5 text-sm font-normal outline-none"><option value="user">User</option><option value="psychologist">Psychologist</option><option value="admin">Admin</option></select></label><button disabled={isCreating} className="self-end rounded-full bg-primary px-5 py-3 text-xs font-bold text-on-primary shadow-[0_3px_0_#121214] disabled:opacity-60">{isCreating ? 'Creating…' : 'Create account'}</button></form>
    <div className="mt-6 overflow-x-auto"><table className="min-w-[760px] w-full text-left text-xs"><thead className="border-b border-surface-container text-on-surface-variant"><tr><th className="px-3 py-3 font-bold">User</th><th className="px-3 py-3 font-bold">Role</th><th className="px-3 py-3 font-bold">Consultant</th><th className="px-3 py-3 font-bold">Status</th><th className="px-3 py-3 font-bold">Actions</th></tr></thead><tbody>{isLoading ? <tr><td className="px-3 py-6 text-on-surface-variant" colSpan="5">Loading users…</td></tr> : adminUsers.map((user) => <tr className="border-b border-surface-container/70" key={user.id}><td className="px-3 py-4">{editingId === user.id ? <div className="flex gap-2"><input value={draftName} onChange={(event) => setDraftName(event.target.value)} className="w-40 rounded-lg bg-surface-container px-2 py-1.5 outline-none focus:ring-2 focus:ring-primary/30" /><button disabled={savingId === user.id} onClick={() => saveName(user)} className="rounded-lg bg-primary px-2 py-1.5 font-bold text-on-primary">Save</button></div> : <><div className="font-bold text-on-surface">{user.name}</div><div className="text-on-surface-variant">{user.email}</div></>}</td><td className="px-3 py-4"><select disabled={user.id === authUser?.id || savingId === user.id} value={user.role} onChange={(event) => updateRole(user, event.target.value)} className="rounded-lg bg-surface-container px-2 py-1.5 font-bold text-on-surface disabled:opacity-50"><option value="user">User</option><option value="psychologist">Psychologist</option><option value="admin">Admin</option></select></td><td className="px-3 py-4 text-on-surface-variant">{user.psychologistName || '—'}</td><td className="px-3 py-4"><span className={`rounded-full px-2 py-1 font-bold ${user.isBanned ? 'bg-error-container text-on-error-container' : 'bg-primary-container text-on-primary-container'}`}>{user.isBanned ? 'Blocked' : 'Active'}</span></td><td className="px-3 py-4"><div className="flex gap-2"><button onClick={() => beginEdit(user)} className="rounded-lg bg-surface-container px-2.5 py-1.5 font-bold text-on-surface hover:bg-surface-container-high">Edit</button><button disabled={user.id === authUser?.id || savingId === user.id} onClick={() => toggleBan(user)} className={`rounded-lg px-2.5 py-1.5 font-bold disabled:opacity-50 ${user.isBanned ? 'bg-primary-container text-on-primary-container' : 'bg-error-container text-on-error-container'}`}>{user.isBanned ? 'Unblock' : 'Block'}</button></div></td></tr>)}</tbody></table></div>
  </div></section>;
}
