import { useEffect, useMemo, useState } from 'react';
import { useFlow } from '../../context/FlowContext';

const moodMap = {
  Happy: {
    bg: 'bg-primary-container', text: 'text-primary', icon: 'sentiment_very_satisfied',
    summary: { label: 'Happy: Green · positive energy', emoji: '🌿', container: 'bg-primary-container', eyebrow: 'bg-surface-container-lowest/80 text-on-primary-container', heading: 'text-on-surface', copy: 'text-on-surface', face: 'text-[#1f2c20]', metric: 'bg-surface-container-lowest/90', metricLabel: 'text-on-surface-variant', metricValue: 'text-on-surface', metricNote: 'text-primary' },
  },
  Angry: {
    bg: 'bg-error-container', text: 'text-error', icon: 'sentiment_very_dissatisfied',
    summary: { label: 'Angry: Red · give space to calm down', emoji: '🔥', container: 'bg-error-container', eyebrow: 'bg-surface-container-lowest/80 text-on-error-container', heading: 'text-on-error-container', copy: 'text-on-error-container', face: 'text-error', metric: 'bg-surface-container-lowest/90', metricLabel: 'text-on-surface-variant', metricValue: 'text-on-surface', metricNote: 'text-error' },
  },
  Sleepy: {
    bg: 'bg-[#cde5ff]', text: 'text-[#1b3d63]', icon: 'bedtime',
    summary: { label: 'Sleepy: Night blue · time to restore your energy', emoji: '🌙', container: 'bg-[#24324a]', eyebrow: 'bg-white/15 text-white', heading: 'text-white', copy: 'text-white/85', face: 'text-[#dbeafe]', metric: 'bg-white/10', metricLabel: 'text-white/65', metricValue: 'text-white', metricNote: 'text-[#b9d5ff]' },
  },
  Bored: {
    bg: 'bg-tertiary-container', text: 'text-tertiary', icon: 'sentiment_neutral',
    summary: { label: 'Bored: Soft purple · try something new', emoji: '✨', container: 'bg-tertiary-container', eyebrow: 'bg-surface-container-lowest/80 text-on-tertiary-container', heading: 'text-on-surface', copy: 'text-on-surface', face: 'text-tertiary', metric: 'bg-surface-container-lowest/90', metricLabel: 'text-on-surface-variant', metricValue: 'text-on-surface', metricNote: 'text-tertiary' },
  },
};
const moodStyle = (mood) => moodMap[mood] || moodMap.Happy;
const moodSummary = (mood) => moodStyle(mood).summary;

export default function SafeHarbor() {
  const { selectedMood, streakDays, authUser, vaultEntries, weeklyMetrics, psychologists, loadPsychologists, selectPsychologist, disconnectPsychologist, consentChoice, authError } = useFlow();
  const [activeDay, setActiveDay] = useState(null); const [isSelecting, setIsSelecting] = useState(false); const [isDisconnecting, setIsDisconnecting] = useState(false);
  const selectedConsultant = psychologists.find((item) => item.id === authUser?.psychologistId);
  const calendarMonth = useMemo(() => new Date(2026, 8, 1), []);
  const monthMood = useMemo(() => {
    const result = new Map();
    vaultEntries.forEach((entry) => { const date = new Date(entry.createdAt || entry.timestamp); if (!Number.isNaN(date.getTime()) && date.getFullYear() === 2026 && date.getMonth() === 8) result.set(date.getDate(), entry); });
    return result;
  }, [vaultEntries]);
  const counts = useMemo(() => ['Happy', 'Angry', 'Sleepy', 'Bored'].reduce((all, mood) => ({ ...all, [mood]: [...monthMood.values()].filter((entry) => entry.mood === mood).length }), {}), [monthMood]);
  const sleep = weeklyMetrics.filter((item) => item.sleepHours != null).map((item) => item.sleepHours); const stress = weeklyMetrics.filter((item) => item.stressScore != null).map((item) => item.stressScore);
  const averageSleep = sleep.length ? Math.round((sleep.reduce((total, value) => total + value, 0) / sleep.length) * 10) / 10 : '—';
  const averageStress = stress.length ? Math.round(stress.reduce((total, value) => total + value, 0) / stress.length) : '—';
  useEffect(() => { if (authUser?.role === 'user') void loadPsychologists(); }, [authUser?.id]);
  const choose = async (psychologist) => { setIsSelecting(true); try { await selectPsychologist(psychologist.id, consentChoice !== false); } finally { setIsSelecting(false); } };
  const disconnect = async () => { setIsDisconnecting(true); try { await disconnectPsychologist(); } finally { setIsDisconnecting(false); } };
  const firstWeekday = calendarMonth.getDay(); const days = Array.from({ length: 30 }, (_, index) => index + 1); const summary = moodSummary(selectedMood);
  return <section className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-12">
    <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><span className="inline-flex items-center gap-2 rounded-full bg-primary-container px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-on-primary-container"><span className="h-2 w-2 rounded-full bg-primary" />Session complete · Mood Garden sync</span><h1 className="mt-2 text-3xl font-bold tracking-tight text-on-surface sm:text-5xl">Your Mind Feels Lighter! 🎉</h1><p className="mt-2 max-w-2xl text-sm font-medium text-on-surface-variant">See your emotional progress, daily mood calendar, and a summary of your mind's recovery in a transparent and secure way.</p></div><div className="rounded-full bg-surface-container-lowest p-2 text-xs font-bold shadow-[0_3px_0_#121214]"><span className="rounded-full bg-secondary-container px-3 py-1.5 text-on-secondary-container">🔥 {streakDays} Day Streak</span></div></div>
    <div className="grid gap-7 lg:grid-cols-12"><div className="space-y-7 lg:col-span-8"><article className={`relative overflow-hidden rounded-[2rem] p-6 shadow-[0_5px_0_#121214] transition-colors duration-300 sm:p-8 ${summary.container}`}><div className={`absolute right-6 top-6 hidden h-28 w-28 items-center justify-center rounded-full bg-surface-container-lowest/55 sm:flex ${summary.face}`}><MoodFace mood={selectedMood} /></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-wider ${summary.eyebrow}`}>Monthly Mood Summary · September 2026</span><h2 className={`mt-3 text-4xl font-bold ${summary.heading}`}>{selectedMood} <span aria-hidden="true">{summary.emoji}</span></h2><p className={`mt-1 max-w-lg text-sm font-medium ${summary.copy}`}>A summary of your sleep, stress level, and streak based on the Daily Pulse data you filled in yourself.</p><div className="mt-6 grid max-w-xl grid-cols-3 gap-3"><Metric label="Sleep duration" value={averageSleep === '—' ? '—' : `${averageSleep} hrs`} note="Average 😴" style={summary}/><Metric label="Stress level" value={averageStress} note={averageStress === '—' ? 'No data yet' : averageStress >= 70 ? 'High' : averageStress >= 40 ? 'Moderate' : 'Low'} style={summary}/><Metric label="Streak" value={`${streakDays} days`} note="Streak 🔥" style={summary}/></div></article>
      <article className="relative rounded-[2rem] border border-surface-container bg-surface-container-lowest p-5 shadow-[0_5px_0_#121214] sm:p-7"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-2xl font-bold text-on-surface"><span className="material-symbols-outlined text-primary">calendar_month</span>Mood Calendar</h2><p className="mt-1 text-xs font-medium text-on-surface-variant">September 2026 · Click a date to see details.</p></div><span className="rounded-full bg-surface-container-low px-4 py-2 text-xs font-bold">Sep 2026</span></div><div className="mt-6 grid grid-cols-7 gap-2 text-center text-[11px] font-bold text-on-surface-variant">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((day) => <span key={day}>{day}</span>)}</div><div className="mt-3 grid grid-cols-7 gap-2">{Array.from({ length: firstWeekday }).map((_, index) => <div key={`blank-${index}`} className="aspect-square rounded-xl bg-surface-container-low" />)}{days.map((day) => { const entry = monthMood.get(day); const style = moodStyle(entry?.mood); return <button key={day} onClick={() => setActiveDay({ day, entry })} className={`aspect-square rounded-xl p-1 text-center shadow-[0_2px_0_#121214] transition-transform hover:scale-105 ${entry ? style.bg : 'bg-surface-container-low'}`}><span className={`material-symbols-outlined mt-1 block text-lg ${entry ? 'text-on-surface' : 'text-on-surface-variant/40'}`}>{entry ? style.icon : '·'}</span><span className={`block text-[10px] font-bold ${entry ? style.text : 'text-on-surface-variant/60'}`}>{day}</span></button>})}</div><div className="mt-5 flex flex-wrap justify-between gap-3 border-t border-surface-container pt-4 text-xs">{Object.entries(counts).map(([mood, total]) => <span className="flex items-center gap-1.5" key={mood}><span className={`h-3 w-3 rounded-full ${moodStyle(mood).bg}`} />{mood} ({total})</span>)}</div>{activeDay && <CalendarDetail detail={activeDay} onClose={() => setActiveDay(null)} />}</article></div>
      <aside className="space-y-5 lg:col-span-4"><article className="rounded-[2rem] border border-surface-container bg-surface-container-lowest p-6 shadow-[0_5px_0_#121214]"><span className="text-xs font-bold uppercase tracking-widest text-tertiary">Chat with consultant</span>{selectedConsultant ? <div className="mt-4"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold text-on-surface">{selectedConsultant.name}</h2><p className="mt-1 text-xs text-on-surface-variant">Your consultant is now locked in.</p></div><span className="material-symbols-outlined rounded-full bg-tertiary-container p-3 text-on-tertiary-container">lock</span></div><p className="mt-4 rounded-2xl bg-surface-container p-3 text-xs leading-relaxed text-on-surface-variant">{authUser.shareDataWithPsychologist ? 'Your data has been shared with the consultant. Use the floating chat at the bottom right to talk.' : 'Private chat is active. Your Daily Pulse data has not been shared.'}</p><button disabled={isDisconnecting} onClick={disconnect} className="mt-3 w-full rounded-full bg-error-container py-2.5 text-xs font-bold text-on-error-container disabled:opacity-60">{isDisconnecting ? 'Disconnecting?' : 'Disconnect from consultant'}</button></div> : <><h2 className="mt-2 text-xl font-bold text-on-surface">Choose your consultant</h2><p className="mt-1 text-xs text-on-surface-variant">Your choice will be locked in once you select.</p><div className="mt-4 space-y-3">{psychologists.map((psychologist) => <button disabled={isSelecting} onClick={() => choose(psychologist)} key={psychologist.id} className="w-full rounded-2xl bg-surface-container p-4 text-left transition-colors hover:bg-tertiary-container"><div className="font-bold text-on-surface">{psychologist.name}</div><div className="mt-1 text-xs text-on-surface-variant">Careflow Psychologist · choose consultant</div></button>)}</div></>}</article><article className="rounded-[2rem] bg-inverse-surface p-6 text-inverse-on-surface shadow-[0_5px_0_#121214]"><span className="text-xs font-bold uppercase tracking-widest text-inverse-primary">Mood support</span><h2 className="mt-2 text-xl font-bold">Your feelings are valid.</h2><p className="mt-2 text-sm text-inverse-on-surface/80">If you need someone to talk to, use the consultation button or chat with your chosen consultant.</p></article>{authError && <p role="alert" className="rounded-xl bg-error-container px-3 py-2 text-xs font-semibold text-on-error-container">{authError}</p>}</aside></div>
  </section>;
}
function Metric({ label, value, note, style }) { return <div className={`rounded-2xl p-3 shadow-[0_2px_0_#121214] ${style.metric}`}><span className={`text-[10px] font-bold uppercase ${style.metricLabel}`}>{label}</span><strong className={`mt-1 block text-lg ${style.metricValue}`}>{value}</strong><span className={`text-[10px] font-semibold ${style.metricNote}`}>{note}</span></div>; }
function MoodFace({ mood }) {
  const expression = mood === 'Angry'
    ? <><path d="M28 37 43 42M72 37 57 42M31 51h12M57 51h12M38 71Q50 63 62 71" /></>
    : mood === 'Sleepy'
      ? <><path d="M29 45Q37 52 45 45M55 45Q63 52 71 45M38 67Q50 75 62 67" /></>
      : mood === 'Bored'
        ? <><circle cx="36" cy="44" r="3" fill="currentColor" stroke="none" /><circle cx="64" cy="44" r="3" fill="currentColor" stroke="none" /><path d="M37 67h26" /></>
        : <><path d="M28 43Q36 30 44 43M56 43Q64 30 72 43M31 62Q50 84 69 62" /><circle cx="24" cy="58" r="5" fill="#fec5a7" stroke="none" /><circle cx="76" cy="58" r="5" fill="#fec5a7" stroke="none" /></>;
  return <svg viewBox="0 0 100 100" className="h-20 w-20" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="6" aria-hidden="true">{expression}</svg>;
}
function CalendarDetail({ detail, onClose }) { const entry = detail.entry; const style = moodStyle(entry?.mood); return <div className="absolute inset-0 z-20 flex items-center justify-center rounded-[2rem] bg-black/40 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-[2rem] border-2 border-[#121214] bg-surface-container-lowest p-6 shadow-[0_8px_0_#121214]"><button onClick={onClose} className="float-right flex h-9 w-9 items-center justify-center rounded-full bg-surface-container text-on-surface">×</button><span className="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant">Calendar note details</span><div className="mt-5 flex items-center gap-3"><span className={`flex h-14 w-14 items-center justify-center rounded-2xl text-xl font-bold ${entry ? style.bg : 'bg-surface-container'}`}>{detail.day}</span><div><h3 className="text-lg font-bold text-on-surface">{entry ? `Mood recorded: ${entry.mood}` : 'No mood recorded yet'}</h3><p className="text-xs font-semibold text-primary">Status: {entry?.mood || '—'}</p></div></div><button onClick={onClose} className="mt-6 w-full rounded-full bg-primary py-3 text-xs font-bold text-on-primary">Close Note</button></div></div>; }
